dist: xenial
sudo: enabled
language: c

install:
  - make build-depends
  - sudo apt-get -y install debian-archive-keyring

script:
  - make test CONFIG_DISABLE_KVM=yes
  - sha1sum output/*
  - ls -al output/*

# TODO
# - auto deploy the output files to a github release if this is a tagged commit
# - Push the rendered document svg + pdf output to somewhere
