sudo: enabled

language: c

install:
  - make build-depends
  - sudo apt-get -y install debian-archive-keyring dpkg=1.17.5ubuntu5.8

# See the Ubuntu section in the debian/README file for more details, but this
# is a good example of why CI is useful /before/ shipping a product..
#
# Also, the age of the debian-archive-keyring (2012) is simply concerning. So,
# I have to manually add the debian stable release keys
before_script:
  - sudo sed -i '989s/$forceyes//' /usr/sbin/multistrap
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF0F382A1A7B6500

script:
  - make test CONFIG_DISABLE_KVM=yes
  - sha1sum output/*
  - ls -al output/*

# TODO
# - auto deploy the output files to a github release if this is a tagged commit
# - Push the rendered document svg + pdf output to somewhere
